import { Product } from '@/types';

export const hatProduct: Product = {
  id: '1',
  name: 'Premium Wool Fedora Hat',
  description: 'A classic wool fedora hat with a timeless design. Perfect for both casual and formal occasions. Features a soft, comfortable fit and durable construction.',
  price: 89.99,
  originalPrice: 129.99,
  images: [
    'https://images.unsplash.com/photo-1556306535-38febf6782e7?w=800&h=800&fit=crop',
    'https://images.unsplash.com/photo-1572307480813-ceb0e59d8325?w=800&h=800&fit=crop',
    'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800&h=800&fit=crop',
    'https://images.unsplash.com/photo-1556306535-38febf6782e7?w=800&h=800&fit=crop&crop=face',
  ],
  colors: [
    { id: '1', name: 'Black', hex: '#000000', available: true },
    { id: '2', name: 'Brown', hex: '#8B4513', available: true },
    { id: '3', name: 'Navy', hex: '#000080', available: true },
    { id: '4', name: 'Gray', hex: '#808080', available: false },
  ],
  sizes: [
    { id: '1', name: 'S', available: true },
    { id: '2', name: 'M', available: true },
    { id: '3', name: 'L', available: true },
    { id: '4', name: 'XL', available: false },
  ],
  category: 'Hats',
  brand: 'Elegant Headwear',
  rating: 4.8,
  reviewCount: 127,
  inStock: true,
  tags: ['fedora', 'wool', 'classic', 'formal', 'casual'],
  features: [
    '100% Wool construction',
    'Soft, comfortable fit',
    'Timeless design',
    'Suitable for all seasons',
    'Handcrafted quality',
  ],
};

export const relatedProducts: Product[] = [
  {
    id: '2',
    name: 'Leather Baseball Cap',
    description: 'A stylish leather baseball cap with adjustable fit.',
    price: 45.99,
    images: ['https://images.unsplash.com/photo-1556306535-38febf6782e7?w=800&h=800&fit=crop'],
    colors: [{ id: '1', name: 'Brown', hex: '#8B4513', available: true }],
    sizes: [{ id: '1', name: 'One Size', available: true }],
    category: 'Hats',
    brand: 'Elegant Headwear',
    rating: 4.5,
    reviewCount: 89,
    inStock: true,
    tags: ['baseball', 'leather', 'casual'],
    features: ['Genuine leather', 'Adjustable fit', 'Classic design'],
  },
  {
    id: '3',
    name: 'Wool Beanie',
    description: 'A warm and cozy wool beanie for cold weather.',
    price: 29.99,
    images: ['https://images.unsplash.com/photo-1572307480813-ceb0e59d8325?w=800&h=800&fit=crop'],
    colors: [{ id: '1', name: 'Black', hex: '#000000', available: true }],
    sizes: [{ id: '1', name: 'One Size', available: true }],
    category: 'Hats',
    brand: 'Elegant Headwear',
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    tags: ['beanie', 'wool', 'winter'],
    features: ['100% Wool', 'Warm and cozy', 'One size fits all'],
  },
];
